sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t php-docker-apache-example . --no-cache

script:
  - docker run php-docker-apache-example /bin/bash -c "./vendor/bin/phpunit tests/tests.php"