sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t php-docker-apache-example .

script:
  - docker run php-docker-apache-example ./vendor/bin/phpunit tests/tests.php 